name=Rudesheim-Board-ESP32
version=0.0.1
author=test
maintainer=test
sentence=Rudesheim layer 2: Board interface implementation for ESP32.
category=Other
url=
architectures=esp32
depends=Rudesheim-Base
